'use strict';
const $=s=>document.querySelector(s);let ads=[],visible=[],kind='all',limit=36,selected=null,lastFocus=null;
const statusLabels={approved:'ผ่านการตรวจแล้ว',draft:'ร่าง / ตัวอย่าง',needs_review:'รอตรวจ',reference_only:'ใช้ศึกษาเท่านั้น'};
function node(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;}
function safeUrl(raw){try{const u=new URL(raw,location.href);return u.protocol==='https:'||(u.origin===location.origin&&u.protocol==='http:')?u.href:null;}catch{return null;}}
function assetElement(a,title){const u=safeUrl(a?.url);if(!u)return node('div','ไม่มีภาพตัวอย่าง','placeholder');const e=document.createElement(a.kind==='video'?'video':'img');e.src=u;if(a.kind==='video')e.controls=true;else{e.alt=title;e.loading='lazy';e.addEventListener('error',()=>e.replaceWith(node('div','ภาพอ้างอิงไม่พร้อมใช้งาน','placeholder')),{once:true});}return e;}
function filter(){const q=$('#search').value.toLocaleLowerCase();visible=ads.filter(a=>(kind==='all'||a.kind===kind)&&(!$('#angle').value||a.angle===$('#angle').value)&&(!$('#status').value||a.status===$('#status').value)&&[a.title,a.brand,a.caption,a.angle].join(' ').toLocaleLowerCase().includes(q));limit=36;render();}
function render(){const grid=$('#grid');grid.replaceChildren();$('#count').textContent=`${visible.length} ชิ้น · ${visible.filter(a=>a.caption).length} ชิ้นมีแคปชั่น`;for(const ad of visible.slice(0,limit)){const card=node('button',null,'card');card.setAttribute('aria-label',ad.title);card.append(assetElement(ad.assets?.[0],ad.title));const body=node('div',null,'card-body');body.append(node('p',`${ad.brand} · ${ad.angle}`,'meta'),node('h2',ad.title),node('span',statusLabels[ad.status]||'รอตรวจ','badge'));card.append(body);card.onclick=()=>open(ad);grid.append(card);}if(!visible.length)grid.append(node('p','ไม่พบแอดตามตัวกรองนี้ ลองเปลี่ยนคำค้นหรือสถานะ'));$('#more').hidden=visible.length<=limit;}
function link(label,url,download=false){const u=safeUrl(url);if(!u)return;const a=node('a',label);a.href=u;if(download)a.download='';else{a.target='_blank';a.rel='noopener noreferrer';}$('#links').append(a);}
function open(ad){selected=ad;lastFocus=document.activeElement;$('#detail-title').textContent=ad.title;$('#detail-meta').textContent=`${ad.brand} · ${ad.angle}`;$('#detail-status').textContent=statusLabels[ad.status]||'รอตรวจ';$('#detail-note').textContent=ad.kind==='reference'?'ใช้ศึกษาโครงสร้างและมุมขาย สร้างภาพและข้อความใหม่เป็นของคุณ':ad.demo?'ตัวอย่างสำหรับฝึกใช้งาน ยังใช้ยิงแอดไม่ได้':ad.status==='approved'?'แพ็กนี้ผ่านการตรวจเนื้อหาแล้ว ตรวจการตั้งค่าแคมเปญของคุณก่อนยิงแอด': 'ตรวจภาพ ข้อเสนอ ราคา และคำกล่าวอ้างก่อนนำไปใช้';$('#caption').textContent=ad.caption||'ชิ้นนี้ยังไม่มีแคปชั่น';$('#copy').disabled=!ad.caption;$('#message').textContent='';$('#media').replaceChildren(...(ad.assets||[]).map(a=>assetElement(a,ad.title)));$('#links').replaceChildren();if(ad.source?.url)link('เปิดแหล่งอ้างอิง',ad.source.url);if(ad.destination)link('เปิดหน้าปลายทาง',ad.destination);if(ad.kind==='original'&&ad.status==='approved'&&ad.download)link('ดาวน์โหลดภาพ + แคปชั่น (.zip)',ad.download,true);$('#detail').showModal();}
$('#close').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>lastFocus?.focus());$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(selected.caption);$('#message').textContent='คัดลอกแคปชั่นแล้ว';}catch{$('#message').textContent='คัดลอกอัตโนมัติไม่ได้ ให้เลือกข้อความด้านบนแล้วคัดลอก';}};
document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(t=>t.classList.toggle('active',t===b));filter();});['search','angle','status'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',filter));$('#more').onclick=()=>{limit+=36;render();};
fetch('catalog.json').then(r=>{if(!r.ok)throw Error('load');return r.json();}).then(data=>{ads=data;[...new Set(ads.map(a=>a.angle))].sort().forEach(a=>{const o=node('option',a);o.value=a;$('#angle').append(o);});filter();}).catch(()=>{$('#count').textContent='โหลดคลังแอดไม่ได้ ลองรีเฟรชหน้า หรือติดต่อทีมดูแล';});

// Students change these labels and colors in student/site.json, not in this script.
fetch('site.json').then(r=>{if(!r.ok)return null;return r.json();}).then(site=>{
  if(!site)return;
  document.title=site.name+' · '+site.subtitle;
  const labels={'#brand-name':'name','#brand-subtitle':'subtitle','.eyebrow':'eyebrow','.intro h1':'headline','.intro > div > p:last-child':'description','footer':'footer'};
  for(const [selector,key] of Object.entries(labels)){const element=$(selector);if(element&&typeof site[key]==='string')element.textContent=site[key];}
  for(const [key,value] of Object.entries(site.colors||{})){if(['bg','surface','gold','ink','muted','line'].includes(key)&&/^#[0-9a-fA-F]{6}$/.test(value))document.documentElement.style.setProperty('--'+key,value);}
}).catch(()=>{});
